import type { TemplatePaletteOverrides } from "./types";

/**
 * Paleta Pi runtime — design system CI puro.
 *
 * Valores são `var(--ci-*)` / `color-mix(... --ci- ...)` (SSOT em ciTokenSsot.ts).
 * Sem tabela hex/rgba intermediária: o runtime aplica isto directamente sob template=pi.
 * Alpha não lê este módulo (early-return no ThemeTemplateContext).
 *
 * Resíduos deliberados fora do SSOT (sem equivalência CI clara):
 *   #C8845A (status progress dark), #6dbc88 / #1a3a22 (status done),
 *   sombras rgba(0,0,0,*).
 * Overrides de utilizador (Fase 6) continuam a ganhar no merge.
 */
export const PI_PALETTE_OVERRIDES: TemplatePaletteOverrides = {
  dark: {
    black: "var(--ci-iron-deep)",
    navy: "var(--ci-iron-deep)",
    "blue-dark": "var(--ci-dark-raised)",
    "blue-mid": "var(--ci-iron)",
    "blue-light": "var(--ci-prussian-600)",
    primary: "var(--ci-prussian-600)",
    "text-main": "var(--ci-chalk)",
    "text-muted": "var(--ci-chalk-dim)",
    glass: "color-mix(in srgb, var(--ci-chalk-dim) 6%, transparent)",
    border: "var(--ci-iron)",
    "bg-toolbar": "var(--ci-dark-raised)",
    "border-toolbar": "var(--ci-iron)",
    "bg-item-hover": "color-mix(in srgb, var(--ci-chalk-dim) 10%, transparent)",
    "border-item-hover": "color-mix(in srgb, var(--ci-chalk-dim) 15%, transparent)",
    "bg-selected": "color-mix(in srgb, var(--ci-prussian-600) 25%, transparent)",
    "border-selected": "var(--ci-prussian-600)",
    "bg-selected-icon": "color-mix(in srgb, var(--ci-prussian-600) 30%, transparent)",
    "bg-icon": "color-mix(in srgb, var(--ci-chalk-dim) 5%, transparent)",
    "border-icon": "color-mix(in srgb, var(--ci-chalk-dim) 12%, transparent)",
    "bg-icon-hover": "color-mix(in srgb, var(--ci-chalk-dim) 15%, transparent)",
    "border-icon-hover": "color-mix(in srgb, var(--ci-chalk-dim) 22%, transparent)",
    "toolbar-border": "var(--ci-iron)",
    "viewer-toolbar-bg": "var(--ci-iron-deep)",
    "top-toolbar-bg": "var(--ci-iron-deep)",
    "viewer-toolbar-shadow": "0 1px 0 rgba(0,0,0,0.35)",
    "viewer-toolbar-inset": "inset 0 -1px 0 color-mix(in srgb, var(--ci-chalk-dim) 8%, transparent)",
    "viewer-toolbar-icon": "var(--ci-chalk)",
    "viewer-toolbar-hover-bg": "color-mix(in srgb, var(--ci-chalk-dim) 10%, transparent)",
    "toolbar-pressed-bg": "color-mix(in srgb, var(--ci-prussian-600) 25%, transparent)",
    "toolbar-pressed-ring": "var(--ci-prussian-600)",
    "focus-ring": "color-mix(in srgb, var(--ci-prussian-200) 50%, transparent)",
    "scrollbar-track": "color-mix(in srgb, var(--ci-chalk-dim) 5%, transparent)",
    "scrollbar-thumb": "color-mix(in srgb, var(--ci-chalk-dim) 20%, transparent)",
    "piece-toolbar-bg": "var(--ci-iron-deep)",
    "overlay-backdrop": "color-mix(in srgb, var(--ci-iron-deep) 55%, transparent)",
    "modal-bg": "var(--ci-dark-card)",
    "modal-border": "var(--ci-iron)",
    "modal-shadow": "0 24px 60px rgba(0,0,0,0.45)",
    "btn-ghost-bg": "color-mix(in srgb, var(--ci-chalk-dim) 6%, transparent)",
    "btn-ghost-border": "var(--ci-iron)",
    "list-item-bg": "var(--ci-dark-raised)",
    "list-item-border": "var(--ci-iron)",
    "card-bg": "var(--ci-dark-card)",
    "card-border": "var(--ci-iron)",
    "input-bg": "var(--ci-dark-raised)",
    "input-border": "var(--ci-iron)",
    "popover-bg": "var(--ci-dark-card)",
    "popover-border": "var(--ci-iron)",
    "popover-shadow": "0 18px 40px rgba(0,0,0,0.45)",
    "panel-left-bg": "var(--ci-dark-raised)",
    "panel-left-shadow": "1px 0 0 rgba(0,0,0,0.08)",
    "panel-footer-bg": "var(--ci-dark-raised)",
    "panel-footer-border": "var(--ci-iron)",
    divider: "var(--ci-iron)",
    "button-ghost-bg": "color-mix(in srgb, var(--ci-chalk-dim) 6%, transparent)",
    "button-ghost-border": "var(--ci-iron)",
    "button-ghost-hover": "color-mix(in srgb, var(--ci-chalk-dim) 16%, transparent)",
    "accent-button-bg": "color-mix(in srgb, var(--ci-prussian-600) 18%, transparent)",
    "accent-button-border": "var(--ci-prussian-600)",
    "workspace-gradient-start": "var(--ci-dark-raised)",
    "workspace-gradient-end": "var(--ci-iron-deep)",
    "workspace-footer-bg": "var(--ci-dark-raised)",
    "workspace-footer-border": "var(--ci-iron)",
    "loading-overlay": "color-mix(in srgb, var(--ci-iron-deep) 35%, transparent)",
    "spinner-border": "color-mix(in srgb, var(--ci-chalk-dim) 30%, transparent)",
    "spinner-top": "var(--ci-prussian-600)",
    snapline: "color-mix(in srgb, var(--ci-prussian-600) 50%, transparent)",
    "drag-outline": "color-mix(in srgb, var(--ci-prussian-600) 60%, transparent)",
    "door-drawer-bg": "color-mix(in srgb, var(--ci-iron-deep) 45%, transparent)",
    "door-drawer-border": "color-mix(in srgb, var(--ci-chalk-dim) 40%, transparent)",
    "door-drawer-shadow": "0 4px 10px rgba(0,0,0,0.3)",
    "door-drawer-accent": "var(--ci-prussian-600)",
    "door-drawer-open": "color-mix(in srgb, var(--ci-prussian-600) 25%, transparent)",
    "cube-face-border": "var(--ci-iron)",
    "cube-shadow": "rgba(0,0,0,0.3)",
    "panel-resizer-hover": "color-mix(in srgb, var(--ci-chalk-dim) 15%, transparent)",
    "status-todo-bg": "color-mix(in srgb, var(--ci-chalk-dim) 12%, transparent)",
    "status-todo-color": "var(--ci-chalk-dim)",
    "status-todo-border": "color-mix(in srgb, var(--ci-chalk-dim) 30%, transparent)",
    "status-progress-bg": "color-mix(in srgb, var(--ci-sienna-600) 20%, transparent)",
    "status-progress-color": "#C8845A",
    "status-progress-border": "color-mix(in srgb, var(--ci-sienna-600) 30%, transparent)",
    "status-done-bg": "color-mix(in srgb, var(--ci-success) 20%, transparent)",
    "status-done-color": "#6dbc88",
    "status-done-border": "color-mix(in srgb, var(--ci-success) 30%, transparent)",
    "roadmap-row-bg": "color-mix(in srgb, var(--ci-chalk-dim) 3%, transparent)",
    "roadmap-row-border": "color-mix(in srgb, var(--ci-chalk-dim) 8%, transparent)",
    "roadmap-header-bg": "color-mix(in srgb, var(--ci-chalk-dim) 8%, transparent)",
    "stat-card-bg": "color-mix(in srgb, var(--ci-chalk-dim) 4%, transparent)",
    "stat-card-border": "color-mix(in srgb, var(--ci-chalk-dim) 8%, transparent)",
    "progress-track-bg": "color-mix(in srgb, var(--ci-chalk-dim) 10%, transparent)",
    "timeline-item-bg": "color-mix(in srgb, var(--ci-chalk-dim) 3%, transparent)",
    "timeline-item-border": "color-mix(in srgb, var(--ci-chalk-dim) 8%, transparent)",
    "task-row-bg": "color-mix(in srgb, var(--ci-chalk-dim) 3%, transparent)",
    "task-row-border": "color-mix(in srgb, var(--ci-chalk-dim) 8%, transparent)",
    "texture-preview-border": "color-mix(in srgb, var(--ci-chalk-dim) 8%, transparent)",
    "bottom-panel-bg": "var(--ci-dark-card)",
    "bottom-info-panel-inner-bg": "var(--ci-iron-deep)",
    "admin-bg": "var(--ci-iron-deep)",
    "admin-text": "var(--ci-chalk)",
    "admin-sidebar-bg": "var(--ci-dark-raised)",
    "admin-card-bg": "var(--ci-dark-card)",
    "admin-card-border": "var(--ci-iron)",
  },
  light: {
    black: "var(--ci-bg-raised)",
    navy: "var(--ci-chalk)",
    "blue-dark": "var(--ci-bg-raised)",
    "blue-mid": "var(--ci-chalk-dim)",
    "blue-light": "var(--ci-prussian-600)",
    primary: "var(--ci-prussian-600)",
    "text-main": "var(--ci-iron-deep)",
    "text-muted": "var(--ci-iron)",
    glass: "color-mix(in srgb, var(--ci-iron-deep) 6%, transparent)",
    border: "var(--ci-chalk-dim)",
    "bg-toolbar": "var(--ci-chalk)",
    "border-toolbar": "var(--ci-chalk-dim)",
    "bg-item-hover": "color-mix(in srgb, var(--ci-iron-deep) 10%, transparent)",
    "border-item-hover": "color-mix(in srgb, var(--ci-iron-deep) 15%, transparent)",
    "bg-selected": "color-mix(in srgb, var(--ci-prussian-600) 7%, transparent)",
    "border-selected": "var(--ci-prussian-600)",
    "bg-selected-icon": "color-mix(in srgb, var(--ci-prussian-600) 15%, transparent)",
    "bg-icon": "color-mix(in srgb, var(--ci-iron-deep) 5%, transparent)",
    "border-icon": "color-mix(in srgb, var(--ci-iron-deep) 12%, transparent)",
    "bg-icon-hover": "color-mix(in srgb, var(--ci-iron-deep) 15%, transparent)",
    "border-icon-hover": "color-mix(in srgb, var(--ci-iron-deep) 22%, transparent)",
    "toolbar-border": "var(--ci-chalk-dim)",
    "viewer-toolbar-bg": "var(--ci-bg-raised)",
    "top-toolbar-bg": "var(--ci-bg-raised)",
    "viewer-toolbar-shadow": "0 1px 0 rgba(0,0,0,0.06)",
    "viewer-toolbar-inset": "inset 0 -1px 0 color-mix(in srgb, var(--ci-iron-deep) 5%, transparent)",
    "viewer-toolbar-icon": "var(--ci-iron-deep)",
    "viewer-toolbar-hover-bg": "color-mix(in srgb, var(--ci-iron-deep) 10%, transparent)",
    "toolbar-pressed-bg": "color-mix(in srgb, var(--ci-prussian-600) 25%, transparent)",
    "toolbar-pressed-ring": "var(--ci-prussian-600)",
    "focus-ring": "color-mix(in srgb, var(--ci-prussian-600) 45%, transparent)",
    "scrollbar-track": "color-mix(in srgb, var(--ci-iron-deep) 5%, transparent)",
    "scrollbar-thumb": "color-mix(in srgb, var(--ci-iron-deep) 20%, transparent)",
    "piece-toolbar-bg": "var(--ci-bg-raised)",
    "overlay-backdrop": "color-mix(in srgb, var(--ci-iron-deep) 55%, transparent)",
    "modal-bg": "var(--ci-bg-card)",
    "modal-border": "var(--ci-chalk-dim)",
    "modal-shadow": "0 24px 60px rgba(0,0,0,0.15)",
    "btn-ghost-bg": "color-mix(in srgb, var(--ci-iron-deep) 4%, transparent)",
    "btn-ghost-border": "var(--ci-chalk-dim)",
    "list-item-bg": "var(--ci-bg-raised)",
    "list-item-border": "var(--ci-chalk-dim)",
    "card-bg": "var(--ci-bg-card)",
    "card-border": "var(--ci-chalk-dim)",
    "input-bg": "var(--ci-bg-raised)",
    "input-border": "var(--ci-chalk-dim)",
    "popover-bg": "var(--ci-bg-card)",
    "popover-border": "var(--ci-chalk-dim)",
    "popover-shadow": "0 18px 40px rgba(0,0,0,0.12)",
    "panel-left-bg": "var(--ci-bg-raised)",
    "panel-left-shadow": "1px 0 0 rgba(0,0,0,0.05)",
    "panel-footer-bg": "var(--ci-bg-raised)",
    "panel-footer-border": "var(--ci-chalk-dim)",
    divider: "var(--ci-chalk-dim)",
    "button-ghost-bg": "color-mix(in srgb, var(--ci-iron-deep) 4%, transparent)",
    "button-ghost-border": "var(--ci-chalk-dim)",
    "button-ghost-hover": "color-mix(in srgb, var(--ci-iron-deep) 14%, transparent)",
    "accent-button-bg": "color-mix(in srgb, var(--ci-prussian-600) 18%, transparent)",
    "accent-button-border": "var(--ci-prussian-600)",
    "workspace-gradient-start": "var(--ci-bg-raised)",
    "workspace-gradient-end": "var(--ci-chalk)",
    "workspace-footer-bg": "var(--ci-bg-raised)",
    "workspace-footer-border": "var(--ci-chalk-dim)",
    "loading-overlay": "color-mix(in srgb, var(--ci-chalk) 60%, transparent)",
    "spinner-border": "color-mix(in srgb, var(--ci-iron-deep) 20%, transparent)",
    "spinner-top": "var(--ci-prussian-600)",
    snapline: "color-mix(in srgb, var(--ci-prussian-600) 50%, transparent)",
    "drag-outline": "color-mix(in srgb, var(--ci-prussian-600) 60%, transparent)",
    "door-drawer-bg": "color-mix(in srgb, var(--ci-chalk) 75%, transparent)",
    "door-drawer-border": "color-mix(in srgb, var(--ci-iron-deep) 35%, transparent)",
    "door-drawer-shadow": "0 4px 10px rgba(0,0,0,0.1)",
    "door-drawer-accent": "var(--ci-prussian-600)",
    "door-drawer-open": "color-mix(in srgb, var(--ci-prussian-600) 15%, transparent)",
    "cube-face-border": "var(--ci-chalk-dim)",
    "cube-shadow": "rgba(0,0,0,0.15)",
    "panel-resizer-hover": "color-mix(in srgb, var(--ci-iron-deep) 12%, transparent)",
    "status-todo-bg": "color-mix(in srgb, var(--ci-iron-deep) 10%, transparent)",
    "status-todo-color": "var(--ci-iron)",
    "status-todo-border": "color-mix(in srgb, var(--ci-iron-deep) 25%, transparent)",
    "status-progress-bg": "color-mix(in srgb, var(--ci-sienna-600) 8%, transparent)",
    "status-progress-color": "var(--ci-sienna-800)",
    "status-progress-border": "color-mix(in srgb, var(--ci-sienna-600) 30%, transparent)",
    "status-done-bg": "color-mix(in srgb, var(--ci-success) 8%, transparent)",
    "status-done-color": "#1a3a22",
    "status-done-border": "color-mix(in srgb, var(--ci-success) 30%, transparent)",
    "roadmap-row-bg": "color-mix(in srgb, var(--ci-iron-deep) 2%, transparent)",
    "roadmap-row-border": "color-mix(in srgb, var(--ci-iron-deep) 6%, transparent)",
    "roadmap-header-bg": "color-mix(in srgb, var(--ci-iron-deep) 6%, transparent)",
    "stat-card-bg": "color-mix(in srgb, var(--ci-iron-deep) 3%, transparent)",
    "stat-card-border": "color-mix(in srgb, var(--ci-iron-deep) 8%, transparent)",
    "progress-track-bg": "color-mix(in srgb, var(--ci-iron-deep) 10%, transparent)",
    "timeline-item-bg": "color-mix(in srgb, var(--ci-iron-deep) 3%, transparent)",
    "timeline-item-border": "color-mix(in srgb, var(--ci-iron-deep) 8%, transparent)",
    "task-row-bg": "color-mix(in srgb, var(--ci-iron-deep) 3%, transparent)",
    "task-row-border": "color-mix(in srgb, var(--ci-iron-deep) 8%, transparent)",
    "texture-preview-border": "color-mix(in srgb, var(--ci-iron-deep) 8%, transparent)",
    "bottom-panel-bg": "var(--ci-bg-card)",
    "bottom-info-panel-inner-bg": "var(--ci-bg-raised)",
    "admin-bg": "var(--ci-chalk)",
    "admin-text": "var(--ci-iron-deep)",
    "admin-sidebar-bg": "var(--ci-bg-raised)",
    "admin-card-bg": "var(--ci-bg-card)",
    "admin-card-border": "var(--ci-chalk-dim)",
  },
};
