export const theme = {
  colors: {
    background: "var(--navy)",
    surface: "var(--card-bg)",
    surfaceBorder: "var(--card-border)",
    text: "var(--text-main)",
    textMuted: "var(--text-muted)",
    border: "var(--border)",
    primary: "var(--blue-light)",
    primaryText: "#ffffff",
    secondary: "var(--button-ghost-bg)",
    secondaryBorder: "var(--button-ghost-border)",
    secondaryText: "var(--text-main)",
    outlineText: "var(--text-main)",
    inputBg: "var(--input-bg)",
    inputBorder: "var(--input-border)",
    danger: "#dc2626",
    success: "#16a34a",
    focusRing: "var(--focus-ring)",
  },
  spacing: {
    s1: 4,
    s2: 8,
    s3: 12,
    s4: 16,
    s5: 24,
    s6: 32,
    s7: 40,
    s8: 48,
  },
  radius: {
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "20px",
    pill: "999px",
  },
  typography: {
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    h1: { fontSize: 28, fontWeight: 700, lineHeight: 1.2 },
    h2: { fontSize: 18, fontWeight: 600, lineHeight: 1.3 },
    body: { fontSize: 14, fontWeight: 400, lineHeight: 1.55 },
    small: { fontSize: 12, fontWeight: 400, lineHeight: 1.45 },
    label: { fontSize: 12, fontWeight: 600, lineHeight: 1.45 },
  },
  shadows: {
    xs: "0 1px 2px rgba(0, 0, 0, 0.08)",
    sm: "0 6px 18px rgba(0, 0, 0, 0.12)",
    md: "0 14px 34px rgba(0, 0, 0, 0.16)",
    card: "0 10px 26px rgba(0, 0, 0, 0.13)",
    none: "none",
  },
  components: {
    button: {
      minHeight: 40,
      paddingX: 14,
      paddingY: 9,
      borderWidth: 1,
      primaryBg: "var(--blue-light)",
      primaryBorder: "var(--blue-light)",
      secondaryBg: "var(--button-ghost-bg)",
      secondaryBorder: "var(--button-ghost-border)",
      secondaryHover: "var(--button-ghost-hover)",
      disabledOpacity: 0.6,
    },
    input: {
      minHeight: 42,
      paddingX: 12,
      paddingY: 9,
      borderWidth: 1,
    },
    card: {
      borderWidth: 1,
      padding: 20,
    },
  },
} as const;

export type AppTheme = typeof theme;

export function applyThemeVariables(): void {
  const root = document.documentElement;
  const vars: Record<string, string | number> = {
    "--ui-color-background": theme.colors.background,
    "--ui-color-surface": theme.colors.surface,
    "--ui-color-surface-border": theme.colors.surfaceBorder,
    "--ui-color-text": theme.colors.text,
    "--ui-color-text-muted": theme.colors.textMuted,
    "--ui-color-border": theme.colors.border,
    "--ui-color-primary": theme.colors.primary,
    "--ui-color-primary-text": theme.colors.primaryText,
    "--ui-color-input-bg": theme.colors.inputBg,
    "--ui-color-input-border": theme.colors.inputBorder,
    "--ui-color-danger": theme.colors.danger,
    "--ui-color-focus-ring": theme.colors.focusRing,

    "--ui-space-1": theme.spacing.s1,
    "--ui-space-2": theme.spacing.s2,
    "--ui-space-3": theme.spacing.s3,
    "--ui-space-4": theme.spacing.s4,
    "--ui-space-5": theme.spacing.s5,
    "--ui-space-6": theme.spacing.s6,
    "--ui-space-7": theme.spacing.s7,
    "--ui-space-8": theme.spacing.s8,
    "--ui-space-xxs": theme.spacing.s1,
    "--ui-space-xs": theme.spacing.s2,
    "--ui-space-sm": theme.spacing.s3,
    "--ui-space-md": theme.spacing.s4,
    "--ui-space-lg": theme.spacing.s5,
    "--ui-space-xl": theme.spacing.s6,

    "--ui-radius-sm": theme.radius.sm,
    "--ui-radius-md": theme.radius.md,
    "--ui-radius-lg": theme.radius.lg,
    "--ui-radius-xl": theme.radius.xl,
    "--ui-radius-pill": theme.radius.pill,

    "--ui-font-family": theme.typography.fontFamily,
    "--ui-font-size-h1": `${theme.typography.h1.fontSize}px`,
    "--ui-font-size-h2": `${theme.typography.h2.fontSize}px`,
    "--ui-font-size-body": `${theme.typography.body.fontSize}px`,
    "--ui-font-size-small": `${theme.typography.small.fontSize}px`,
    "--ui-font-size-label": `${theme.typography.label.fontSize}px`,
    "--ui-font-weight-h1": theme.typography.h1.fontWeight,
    "--ui-font-weight-h2": theme.typography.h2.fontWeight,
    "--ui-font-weight-label": theme.typography.label.fontWeight,
    "--ui-line-height-h1": String(theme.typography.h1.lineHeight),
    "--ui-line-height-h2": String(theme.typography.h2.lineHeight),
    "--ui-line-height-body": String(theme.typography.body.lineHeight),
    "--ui-line-height-small": String(theme.typography.small.lineHeight),
    "--ui-line-height-label": String(theme.typography.label.lineHeight),

    "--ui-color-secondary": theme.colors.secondary,
    "--ui-color-secondary-border": theme.colors.secondaryBorder,
    "--ui-color-secondary-text": theme.colors.secondaryText,
    "--ui-color-outline-text": theme.colors.outlineText,
    "--ui-color-success": theme.colors.success,

    "--ui-shadow-card": theme.shadows.card,
    "--ui-shadow-xs": theme.shadows.xs,
    "--ui-shadow-sm": theme.shadows.sm,
    "--ui-shadow-md": theme.shadows.md,
    "--ui-shadow-subtle": theme.shadows.xs,

    "--ui-button-min-height": theme.components.button.minHeight,
    "--ui-button-padding-x": `${theme.components.button.paddingX}px`,
    "--ui-button-padding-y": `${theme.components.button.paddingY}px`,
    "--ui-button-border-width": theme.components.button.borderWidth,
    "--ui-button-primary-bg": theme.components.button.primaryBg,
    "--ui-button-primary-border": theme.components.button.primaryBorder,
    "--ui-button-secondary-bg": theme.components.button.secondaryBg,
    "--ui-button-secondary-border": theme.components.button.secondaryBorder,
    "--ui-button-secondary-hover": theme.components.button.secondaryHover,
    "--ui-button-ghost-bg": theme.components.button.secondaryBg,
    "--ui-button-ghost-border": theme.components.button.secondaryBorder,
    "--ui-button-ghost-hover": theme.components.button.secondaryHover,
    "--ui-button-disabled-opacity": theme.components.button.disabledOpacity,

    "--ui-input-min-height": theme.components.input.minHeight,
    "--ui-input-padding-x": `${theme.components.input.paddingX}px`,
    "--ui-input-padding-y": `${theme.components.input.paddingY}px`,
    "--ui-input-border-width": theme.components.input.borderWidth,

    "--ui-card-padding": `${theme.components.card.padding}px`,
  };

  Object.entries(vars).forEach(([key, value]) => {
    root.style.setProperty(key, String(value));
  });
}
