export type CostRules = {
  priceBaseCabinet: number;
  priceUpperCabinet: number;
  priceTallCabinet: number;
  priceDoor: number;
  priceDrawer: number;
  priceRemate: number;
  priceRodape: number;
  priceAccessory: number;
  priceMdf: number;
  priceAglomerado: number;
  priceMadeira: number;
  priceLacado: number;
  priceVidro: number;
  priceMetal: number;
  costPerMmWidth: number;
  costPerMmHeight: number;
  costPerMmDepth: number;
  costPerHole: number;
  extraCostPerHole: number;
  holeCountMultiplier: number;
  priceHoleDobradica: number;
  priceHoleCorredica: number;
  priceHolePuxador: number;
  priceHoleCavilha: number;
  priceHoleParafuso: number;
  priceHoleMinifix: number;
  priceHolePrateleira: number;
  costPerPiece: number;
  costPerModulePiece: number;
  modulePieceMultiplier: number;
  costPerDoor: number;
  costPerDrawer: number;
  costPerRemate: number;
  volumePerM3: number;
  doorUnit: number;
  drawerUnit: number;
  shelfUnit: number;
  remateUnit: number;
  rodapeUnit: number;
  symmetryBonus: number;
  continuityBonus: number;
  multModern: number;
  multNordic: number;
  multIndustrial: number;
  multMinimalist: number;
  multClassic: number;
  multScandinavian: number;
  multJapandi: number;
  multLuxury: number;
  multMoreFreeSpace: number;
  multMoreStorage: number;
  multMoreSymmetry: number;
  multMoreDepth: number;
  multDesignA: number;
  multDesignB: number;
  multDesignC: number;
  multErgonomics: number;
  multPremium: number;
  multEconomical: number;
};

export const COST_RULES_DEFAULTS: CostRules = {
  priceBaseCabinet: 100,
  priceUpperCabinet: 85,
  priceTallCabinet: 130,
  priceDoor: 14,
  priceDrawer: 11,
  priceRemate: 22,
  priceRodape: 16,
  priceAccessory: 8,
  priceMdf: 1,
  priceAglomerado: 0.75,
  priceMadeira: 1.4,
  priceLacado: 1.25,
  priceVidro: 2.1,
  priceMetal: 1.8,
  costPerMmWidth: 0.02,
  costPerMmHeight: 0.018,
  costPerMmDepth: 0.015,
  costPerHole: 0.5,
  extraCostPerHole: 0.5,
  holeCountMultiplier: 1,
  priceHoleDobradica: 0.8,
  priceHoleCorredica: 0.6,
  priceHolePuxador: 0.4,
  priceHoleCavilha: 0.35,
  priceHoleParafuso: 0.45,
  priceHoleMinifix: 0.55,
  priceHolePrateleira: 0.3,
  costPerPiece: 1.2,
  costPerModulePiece: 1.2,
  modulePieceMultiplier: 1,
  costPerDoor: 14,
  costPerDrawer: 11,
  costPerRemate: 22,
  volumePerM3: 120,
  doorUnit: 14,
  drawerUnit: 11,
  shelfUnit: 5,
  remateUnit: 22,
  rodapeUnit: 16,
  symmetryBonus: -8,
  continuityBonus: -6,
  multModern: 1,
  multNordic: 0.92,
  multIndustrial: 1.08,
  multMinimalist: 0.85,
  multClassic: 1.05,
  multScandinavian: 0.9,
  multJapandi: 0.95,
  multLuxury: 1.22,
  multMoreFreeSpace: 0.78,
  multMoreStorage: 1.18,
  multMoreSymmetry: 1.02,
  multMoreDepth: 1.12,
  multDesignA: 1,
  multDesignB: 0.82,
  multDesignC: 1.15,
  multErgonomics: 1,
  multPremium: 1.2,
  multEconomical: 0.8,
};
