import type { RulesFieldDef } from "../shared/types";
import type { CostRules } from "./rulesDefaults";

export const COST_RULES_FIELDS: RulesFieldDef[] = [
  { key: "priceBaseCabinet", label: "Caixa base", type: "number", min: 0, step: 1, section: "A) Preço por tipo de peça" },
  { key: "priceUpperCabinet", label: "Caixa superior", type: "number", min: 0, step: 1, section: "A) Preço por tipo de peça" },
  { key: "priceTallCabinet", label: "Caixa alta", type: "number", min: 0, step: 1, section: "A) Preço por tipo de peça" },
  { key: "priceDoor", label: "Porta", type: "number", min: 0, step: 1, section: "A) Preço por tipo de peça" },
  { key: "priceDrawer", label: "Gaveta", type: "number", min: 0, step: 1, section: "A) Preço por tipo de peça" },
  { key: "priceRemate", label: "Remate", type: "number", min: 0, step: 1, section: "A) Preço por tipo de peça" },
  { key: "priceRodape", label: "Rodapé", type: "number", min: 0, step: 1, section: "A) Preço por tipo de peça" },
  { key: "priceAccessory", label: "Acessórios", type: "number", min: 0, step: 1, section: "A) Preço por tipo de peça" },
  { key: "priceMdf", label: "MDF", type: "number", min: 0, step: 0.01, section: "B) Preço por material" },
  { key: "priceAglomerado", label: "Aglomerado", type: "number", min: 0, step: 0.01, section: "B) Preço por material" },
  { key: "priceMadeira", label: "Madeira", type: "number", min: 0, step: 0.01, section: "B) Preço por material" },
  { key: "priceLacado", label: "Lacado", type: "number", min: 0, step: 0.01, section: "B) Preço por material" },
  { key: "priceVidro", label: "Vidro", type: "number", min: 0, step: 0.01, section: "B) Preço por material" },
  { key: "priceMetal", label: "Metal", type: "number", min: 0, step: 0.01, section: "B) Preço por material" },
  { key: "costPerMmWidth", label: "Custo por mm largura", type: "number", min: 0, step: 0.001, section: "C) Preço por dimensão" },
  { key: "costPerMmHeight", label: "Custo por mm altura", type: "number", min: 0, step: 0.001, section: "C) Preço por dimensão" },
  { key: "costPerMmDepth", label: "Custo por mm profundidade", type: "number", min: 0, step: 0.001, section: "C) Preço por dimensão" },
  { key: "extraCostPerHole", label: "Custo extra por furo", type: "number", min: 0, step: 0.05, section: "D1) Furos — quantidade", description: "Valor adicional por cada furo estimado no módulo." },
  { key: "holeCountMultiplier", label: "Multiplicador por n.º de furos", type: "number", min: 0, max: 5, step: 0.05, section: "D1) Furos — quantidade" },
  { key: "costPerHole", label: "Peso base por furo (legado)", type: "number", min: 0, step: 0.1, section: "D1) Furos — quantidade" },
  { key: "priceHoleDobradica", label: "Furo dobradiça", type: "number", min: 0, step: 0.05, section: "D2) Furos — por tipo" },
  { key: "priceHoleCorredica", label: "Furo corrediça", type: "number", min: 0, step: 0.05, section: "D2) Furos — por tipo" },
  { key: "priceHolePuxador", label: "Furo puxador", type: "number", min: 0, step: 0.05, section: "D2) Furos — por tipo" },
  { key: "priceHoleCavilha", label: "Furo cavilha", type: "number", min: 0, step: 0.05, section: "D2) Furos — por tipo" },
  { key: "priceHoleParafuso", label: "Furo parafuso", type: "number", min: 0, step: 0.05, section: "D2) Furos — por tipo" },
  { key: "priceHoleMinifix", label: "Furo minifix", type: "number", min: 0, step: 0.05, section: "D2) Furos — por tipo" },
  { key: "priceHolePrateleira", label: "Furo prateleira", type: "number", min: 0, step: 0.05, section: "D2) Furos — por tipo" },
  { key: "costPerModulePiece", label: "Custo por peça do módulo", type: "number", min: 0, step: 0.1, section: "D3) Peças do módulo (complexidade)", description: "Preço relativo por peça estrutural estimada (laterais, tampos, costa, etc.)." },
  { key: "modulePieceMultiplier", label: "Multiplicador peças do módulo", type: "number", min: 0, max: 5, step: 0.05, section: "D3) Peças do módulo (complexidade)" },
  { key: "costPerPiece", label: "Peso base por peça (legado)", type: "number", min: 0, step: 0.1, section: "D3) Peças do módulo (complexidade)" },
  { key: "costPerDoor", label: "Número de portas (peso)", type: "number", min: 0, step: 1, section: "D) Preço por complexidade" },
  { key: "costPerDrawer", label: "Número de gavetas (peso)", type: "number", min: 0, step: 1, section: "D) Preço por complexidade" },
  { key: "costPerRemate", label: "Número de remates (peso)", type: "number", min: 0, step: 1, section: "D) Preço por complexidade" },
  { key: "volumePerM3", label: "Volume (peso/m³)", type: "number", min: 0, section: "Motor heurístico" },
  { key: "doorUnit", label: "Unidade porta", type: "number", min: 0, section: "Motor heurístico" },
  { key: "drawerUnit", label: "Unidade gaveta", type: "number", min: 0, section: "Motor heurístico" },
  { key: "shelfUnit", label: "Unidade prateleira", type: "number", min: 0, section: "Motor heurístico" },
  { key: "remateUnit", label: "Unidade remate", type: "number", min: 0, section: "Motor heurístico" },
  { key: "rodapeUnit", label: "Unidade rodapé", type: "number", min: 0, section: "Motor heurístico" },
  { key: "symmetryBonus", label: "Bónus simetria", type: "number", section: "Motor heurístico" },
  { key: "continuityBonus", label: "Bónus continuidade", type: "number", section: "Motor heurístico" },
  { key: "multModern", label: "Modern", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de estilo" },
  { key: "multNordic", label: "Nórdico", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de estilo" },
  { key: "multIndustrial", label: "Industrial", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de estilo" },
  { key: "multMinimalist", label: "Minimalista", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de estilo" },
  { key: "multClassic", label: "Clássico", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de estilo" },
  { key: "multScandinavian", label: "Escandinavo", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de estilo" },
  { key: "multJapandi", label: "Japandi", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de estilo" },
  { key: "multLuxury", label: "Luxo", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de estilo" },
  { key: "multMoreFreeSpace", label: "Mais espaço", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de variação" },
  { key: "multMoreStorage", label: "Mais armazenamento", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de variação" },
  { key: "multMoreSymmetry", label: "Mais simetria", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de variação" },
  { key: "multMoreDepth", label: "Mais profundidade", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de variação" },
  { key: "multDesignA", label: "Design A", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de design" },
  { key: "multDesignB", label: "Design B", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de design" },
  { key: "multDesignC", label: "Design C", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores de design" },
  { key: "multErgonomics", label: "Ergonomia", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores gerais" },
  { key: "multPremium", label: "Premium", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores gerais" },
  { key: "multEconomical", label: "Económico", type: "number", min: 0.1, max: 3, step: 0.01, section: "E) Multiplicadores gerais" },
];

export type { CostRules };
